/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

@class NSURL;

@interface YTStream : NSObject <NSCopying>
{
    NSURL *URL_;
    int format_;
    BOOL encrypted_;
}

+ (int)selectAdSenseiTagOnWiFi:(BOOL)arg1;
+ (id)selectStreamForVideo:(id)arg1 onWiFi:(BOOL)arg2;
+ (id)streamWithURL:(id)arg1 format:(int)arg2 encrypted:(BOOL)arg3;
@property(readonly, nonatomic) BOOL encrypted; // @synthesize encrypted=encrypted_;
@property(readonly, nonatomic) int format; // @synthesize format=format_;
@property(readonly, nonatomic) NSURL *URL; // @synthesize URL=URL_;
- (id)description;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)dealloc;
- (id)initWithURL:(id)arg1 format:(int)arg2 encrypted:(BOOL)arg3;

@end

